name: Convert Foam Links
on:
  push:
    branches:
      - main

jobs:
  convert-links:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for changes to sync 
        run: sleep 10
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Convert Foam links to standard Markdown
        run: |
          find . -name "*.md" -exec sed -i 's/\[\[\([^]]*\)\]\]/[\1](\1.md)/g' {} +

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Convert Foam links to standard Markdown'
          git push